# Generated by Django 4.1.4 on 2023-01-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_survivor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(
                through='api.QuantityItem', to='api.Item'),
        )
    ]
