# Generated by Django 5.0 on 2023-12-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_survivor_email_survivor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
